import type { Metadata } from "next";
import { GlobalStyles } from "@/app/global-styles";
import { ReactNode } from "react";
import Providers from "@/Providers";
import { ChakraProvider } from "@chakra-ui/react";
import { chakraTheme } from "@/styles/chakraTheme";
import { RecoilRoot } from "recoil";
import Client from "./client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Client>
          <GlobalStyles/>
          <ChakraProvider theme={chakraTheme}>
            <Providers>
              {children}
            </Providers>
          </ChakraProvider>
        </Client>
      </body>
    </html>
  );
}
