import type {Metadata} from 'next'
import {GlobalStyles} from "@/app/global-styles";
import {ReactNode} from "react";
import Providers from "@/Providers";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <Providers>
                <GlobalStyles/>
                {children}
            </Providers>
        </body>
        </html>
    )
}
